# Generated by Django 6.0.2 on 2026-04-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
